"""
GitHub PR skill execution — pushes feature branch and opens a PR for human review.
Loads spec from skill.md. Returns pr_url or None if GitHub not configured.
"""

from src.common.config import settings
from src.common.logging import get_logger

logger = get_logger(__name__)


def create_pull_request(
    repo_url: str,
    feature_branch: str,
    base_branch: str,
    task_id: str,
    goal: str,
    steps: list[dict],
    risk_level: str | None = None,
) -> str | None:
    """
    Open a GitHub PR from feature_branch → base_branch.
    Returns the PR html_url, or None if GitHub is not configured or the call fails.
    """
    if not settings.GITHUB_TOKEN:
        logger.info("github_pr.skipped", reason="GITHUB_TOKEN not set")
        return None

    if not repo_url:
        logger.info("github_pr.skipped", reason="no repo_url")
        return None

    try:
        import requests as _http
        from urllib.parse import urlparse

        parsed = urlparse(repo_url)
        path_parts = parsed.path.strip("/").replace(".git", "").split("/")
        if len(path_parts) < 2:
            logger.warning("github_pr.invalid_repo_url", repo_url=repo_url)
            return None

        owner, repo = path_parts[0], path_parts[1]
        draft = risk_level == "high"

        headers = {
            "Authorization": f"token {settings.GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json",
        }
        payload = {
            "title": _pr_title(goal),
            "body":  _pr_body(goal, steps, task_id),
            "head":  feature_branch,
            "base":  base_branch,
            "draft": draft,
        }

        resp = _http.post(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            json=payload,
            headers=headers,
            timeout=30,
        )

        if resp.status_code in (200, 201):
            pr_url = resp.json().get("html_url", "")
            logger.info("github_pr.created", pr_url=pr_url, draft=draft)
            return pr_url

        logger.warning("github_pr.api_error",
                       status=resp.status_code, body=resp.text[:300])
        return None

    except Exception as exc:
        logger.warning("github_pr.failed", error=str(exc))
        return None


# ── Helpers ───────────────────────────────────────────────────────────────────

def _pr_title(goal: str) -> str:
    return f"feat: {goal[:70]}"


def _pr_body(goal: str, steps: list[dict], task_id: str) -> str:
    steps_md = "\n".join(
        f"- Step {i + 1}: {s.get('action', '')[:80]}"
        for i, s in enumerate(steps)
    )
    return f"""## What
{goal}

## Why
Autonomous agent task `{task_id}` completed all planned steps.

## Steps taken
{steps_md}

## Tests
- [ ] Unit tests pass
- [ ] No existing tests broken

🤖 Generated by Autonomous Agent Platform"""
